server {
    listen 443 ssl;
    server_name localhost;

    # Aponta para os arquivos gerados pelo Python
    ssl_certificate /etc/nginx/certs/fullchain.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}